_wandb:
    value:
        cli_version: 0.18.2
        code_path: code/math/gen_math.py
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.2
            "8":
                - 3
                - 5
            "12": 0.18.2
            "13": windows-amd64
agents:
    value: 2
evaluation_rounds:
    value: 1
rounds:
    value: 3
